# Generated by Django 2.2 on 2021-01-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Show_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV_ShowManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
