# Generated by Django 2.2 on 2021-01-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Show_app', '0002_tv_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TV_ShowManager',
        ),
    ]
